
####timeDelta API
GET http://localhost:5000/api/timeDelta?startTime=1577865600&endTime=1641121445

###taskTrack API
GET http://localhost:5000/api/tasks/retrieve?retrieveAll

###
GET http://localhost:5000/api/tasks/retrieve?eeId=1&taskId=2


### Projects - projectId=1, clientid=3
GET http://localhost:5000/api/projects/retrieve?projectId=1&clientId=3

### Employees - eeId=2, eeFirstName='Brandi'
GET http://localhost:5000/api/employees/retrieve?eeId=2&eeFirstName=b

### Tasks - taskId=1, taskDescription=ee
GET http://localhost:5000/api/tasks/retrieve?taskDescription=eE